import type { AgentCommentaryPhase } from '~/types/context';

export const COMMENTARY_POOL_BY_PHASE: Record<AgentCommentaryPhase, readonly string[]> = {
  plan: [
    'I am mapping your request into clear milestones; so you can see exactly what happens next.',
    'I am mapping your request into clear milestones; so we keep momentum without losing control.',
    'I am mapping your request into clear milestones; so each step has a clear purpose.',
    'I am mapping your request into clear milestones; so the next action is predictable and safe.',
    'I am mapping your request into clear milestones; so we avoid hidden changes.',
    'I am mapping your request into clear milestones; so the plan stays easy to follow.',
    'I am mapping your request with practical checkpoints; so you can see exactly what happens next.',
    'I am mapping your request with practical checkpoints; so we keep momentum without losing control.',
    'I am mapping your request with practical checkpoints; so each step has a clear purpose.',
    'I am mapping your request with practical checkpoints; so the next action is predictable and safe.',
    'I am mapping your request with practical checkpoints; so we avoid hidden changes.',
    'I am mapping your request with practical checkpoints; so the plan stays easy to follow.',
    'I am mapping your request with visible progress points; so you can see exactly what happens next.',
    'I am mapping your request with visible progress points; so we keep momentum without losing control.',
    'I am mapping your request with visible progress points; so each step has a clear purpose.',
    'I am mapping your request with visible progress points; so the next action is predictable and safe.',
    'I am mapping your request with visible progress points; so we avoid hidden changes.',
    'I am mapping your request with visible progress points; so the plan stays easy to follow.',
    'I am mapping your request with low-risk ordering; so you can see exactly what happens next.',
    'I am mapping your request with low-risk ordering; so we keep momentum without losing control.',
    'I am mapping your request with low-risk ordering; so each step has a clear purpose.',
    'I am mapping your request with low-risk ordering; so the next action is predictable and safe.',
    'I am mapping your request with low-risk ordering; so we avoid hidden changes.',
    'I am mapping your request with low-risk ordering; so the plan stays easy to follow.',
    'I am mapping your request with explicit deliverables; so you can see exactly what happens next.',
    'I am mapping your request with explicit deliverables; so we keep momentum without losing control.',
    'I am mapping your request with explicit deliverables; so each step has a clear purpose.',
    'I am mapping your request with explicit deliverables; so the next action is predictable and safe.',
    'I am mapping your request with explicit deliverables; so we avoid hidden changes.',
    'I am mapping your request with explicit deliverables; so the plan stays easy to follow.',
    'I am mapping your request with rollback-safe decisions; so you can see exactly what happens next.',
    'I am mapping your request with rollback-safe decisions; so we keep momentum without losing control.',
    'I am mapping your request with rollback-safe decisions; so each step has a clear purpose.',
    'I am mapping your request with rollback-safe decisions; so the next action is predictable and safe.',
    'I am mapping your request with rollback-safe decisions; so we avoid hidden changes.',
    'I am mapping your request with rollback-safe decisions; so the plan stays easy to follow.',
    'I am mapping your request with test-first verification points; so you can see exactly what happens next.',
    'I am mapping your request with test-first verification points; so we keep momentum without losing control.',
    'I am mapping your request with test-first verification points; so each step has a clear purpose.',
    'I am mapping your request with test-first verification points; so the next action is predictable and safe.',
    'I am mapping your request with test-first verification points; so we avoid hidden changes.',
    'I am mapping your request with test-first verification points; so the plan stays easy to follow.',
    'I am mapping your request with dependency awareness; so you can see exactly what happens next.',
    'I am mapping your request with dependency awareness; so we keep momentum without losing control.',
    'I am mapping your request with dependency awareness; so each step has a clear purpose.',
    'I am mapping your request with dependency awareness; so the next action is predictable and safe.',
    'I am mapping your request with dependency awareness; so we avoid hidden changes.',
    'I am mapping your request with dependency awareness; so the plan stays easy to follow.',
    'I am mapping your request with failure recovery in mind; so you can see exactly what happens next.',
    'I am mapping your request with failure recovery in mind; so we keep momentum without losing control.',
    'I am mapping your request with failure recovery in mind; so each step has a clear purpose.',
    'I am mapping your request with failure recovery in mind; so the next action is predictable and safe.',
    'I am mapping your request with failure recovery in mind; so we avoid hidden changes.',
    'I am mapping your request with failure recovery in mind; so the plan stays easy to follow.',
    'I am mapping your request with user-visible updates; so you can see exactly what happens next.',
    'I am mapping your request with user-visible updates; so we keep momentum without losing control.',
    'I am mapping your request with user-visible updates; so each step has a clear purpose.',
    'I am mapping your request with user-visible updates; so the next action is predictable and safe.',
    'I am mapping your request with user-visible updates; so we avoid hidden changes.',
    'I am mapping your request with user-visible updates; so the plan stays easy to follow.',
  ],
  action: [
    'I am executing the current step while preserving existing behavior; you will see the next visible result shortly.',
    'I am executing the current step while preserving existing behavior; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step while preserving existing behavior; I will keep this step transparent and traceable.',
    'I am executing the current step while preserving existing behavior; I will surface any blocker immediately.',
    'I am executing the current step while preserving existing behavior; I will continue with the next safe action after this.',
    'I am executing the current step while preserving existing behavior; I will post the outcome before moving forward.',
    'I am executing the current step and tracking each output in real time; you will see the next visible result shortly.',
    'I am executing the current step and tracking each output in real time; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step and tracking each output in real time; I will keep this step transparent and traceable.',
    'I am executing the current step and tracking each output in real time; I will surface any blocker immediately.',
    'I am executing the current step and tracking each output in real time; I will continue with the next safe action after this.',
    'I am executing the current step and tracking each output in real time; I will post the outcome before moving forward.',
    'I am executing the current step with runtime safety checks enabled; you will see the next visible result shortly.',
    'I am executing the current step with runtime safety checks enabled; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step with runtime safety checks enabled; I will keep this step transparent and traceable.',
    'I am executing the current step with runtime safety checks enabled; I will surface any blocker immediately.',
    'I am executing the current step with runtime safety checks enabled; I will continue with the next safe action after this.',
    'I am executing the current step with runtime safety checks enabled; I will post the outcome before moving forward.',
    'I am executing the current step while keeping the timeline updated; you will see the next visible result shortly.',
    'I am executing the current step while keeping the timeline updated; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step while keeping the timeline updated; I will keep this step transparent and traceable.',
    'I am executing the current step while keeping the timeline updated; I will surface any blocker immediately.',
    'I am executing the current step while keeping the timeline updated; I will continue with the next safe action after this.',
    'I am executing the current step while keeping the timeline updated; I will post the outcome before moving forward.',
    'I am executing the current step and capturing intermediate results; you will see the next visible result shortly.',
    'I am executing the current step and capturing intermediate results; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step and capturing intermediate results; I will keep this step transparent and traceable.',
    'I am executing the current step and capturing intermediate results; I will surface any blocker immediately.',
    'I am executing the current step and capturing intermediate results; I will continue with the next safe action after this.',
    'I am executing the current step and capturing intermediate results; I will post the outcome before moving forward.',
    'I am executing the current step with guardrails around risky operations; you will see the next visible result shortly.',
    'I am executing the current step with guardrails around risky operations; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step with guardrails around risky operations; I will keep this step transparent and traceable.',
    'I am executing the current step with guardrails around risky operations; I will surface any blocker immediately.',
    'I am executing the current step with guardrails around risky operations; I will continue with the next safe action after this.',
    'I am executing the current step with guardrails around risky operations; I will post the outcome before moving forward.',
    'I am executing the current step while minimizing unnecessary edits; you will see the next visible result shortly.',
    'I am executing the current step while minimizing unnecessary edits; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step while minimizing unnecessary edits; I will keep this step transparent and traceable.',
    'I am executing the current step while minimizing unnecessary edits; I will surface any blocker immediately.',
    'I am executing the current step while minimizing unnecessary edits; I will continue with the next safe action after this.',
    'I am executing the current step while minimizing unnecessary edits; I will post the outcome before moving forward.',
    'I am executing the current step and validating assumptions as I go; you will see the next visible result shortly.',
    'I am executing the current step and validating assumptions as I go; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step and validating assumptions as I go; I will keep this step transparent and traceable.',
    'I am executing the current step and validating assumptions as I go; I will surface any blocker immediately.',
    'I am executing the current step and validating assumptions as I go; I will continue with the next safe action after this.',
    'I am executing the current step and validating assumptions as I go; I will post the outcome before moving forward.',
    'I am executing the current step with clear change boundaries; you will see the next visible result shortly.',
    'I am executing the current step with clear change boundaries; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step with clear change boundaries; I will keep this step transparent and traceable.',
    'I am executing the current step with clear change boundaries; I will surface any blocker immediately.',
    'I am executing the current step with clear change boundaries; I will continue with the next safe action after this.',
    'I am executing the current step with clear change boundaries; I will post the outcome before moving forward.',
    'I am executing the current step while keeping your workspace stable; you will see the next visible result shortly.',
    'I am executing the current step while keeping your workspace stable; I will report the next checkpoint as soon as it lands.',
    'I am executing the current step while keeping your workspace stable; I will keep this step transparent and traceable.',
    'I am executing the current step while keeping your workspace stable; I will surface any blocker immediately.',
    'I am executing the current step while keeping your workspace stable; I will continue with the next safe action after this.',
    'I am executing the current step while keeping your workspace stable; I will post the outcome before moving forward.',
  ],
  verification: [
    'I am validating the latest output against expected behavior; I will move forward only after this clears.',
    'I am validating the latest output against expected behavior; I will share a clear pass/fail summary next.',
    'I am validating the latest output against expected behavior; I will call out any issue before continuing.',
    'I am validating the latest output against expected behavior; I will keep this verification concise and transparent.',
    'I am validating the latest output against expected behavior; I will report what changed and why it is safe.',
    'I am validating the latest output against expected behavior; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output with strict pass/fail checks; I will move forward only after this clears.',
    'I am validating the latest output with strict pass/fail checks; I will share a clear pass/fail summary next.',
    'I am validating the latest output with strict pass/fail checks; I will call out any issue before continuing.',
    'I am validating the latest output with strict pass/fail checks; I will keep this verification concise and transparent.',
    'I am validating the latest output with strict pass/fail checks; I will report what changed and why it is safe.',
    'I am validating the latest output with strict pass/fail checks; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output before unlocking the next action; I will move forward only after this clears.',
    'I am validating the latest output before unlocking the next action; I will share a clear pass/fail summary next.',
    'I am validating the latest output before unlocking the next action; I will call out any issue before continuing.',
    'I am validating the latest output before unlocking the next action; I will keep this verification concise and transparent.',
    'I am validating the latest output before unlocking the next action; I will report what changed and why it is safe.',
    'I am validating the latest output before unlocking the next action; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output and confirming no silent failures; I will move forward only after this clears.',
    'I am validating the latest output and confirming no silent failures; I will share a clear pass/fail summary next.',
    'I am validating the latest output and confirming no silent failures; I will call out any issue before continuing.',
    'I am validating the latest output and confirming no silent failures; I will keep this verification concise and transparent.',
    'I am validating the latest output and confirming no silent failures; I will report what changed and why it is safe.',
    'I am validating the latest output and confirming no silent failures; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output with attention to edge cases; I will move forward only after this clears.',
    'I am validating the latest output with attention to edge cases; I will share a clear pass/fail summary next.',
    'I am validating the latest output with attention to edge cases; I will call out any issue before continuing.',
    'I am validating the latest output with attention to edge cases; I will keep this verification concise and transparent.',
    'I am validating the latest output with attention to edge cases; I will report what changed and why it is safe.',
    'I am validating the latest output with attention to edge cases; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output and documenting the outcome; I will move forward only after this clears.',
    'I am validating the latest output and documenting the outcome; I will share a clear pass/fail summary next.',
    'I am validating the latest output and documenting the outcome; I will call out any issue before continuing.',
    'I am validating the latest output and documenting the outcome; I will keep this verification concise and transparent.',
    'I am validating the latest output and documenting the outcome; I will report what changed and why it is safe.',
    'I am validating the latest output and documenting the outcome; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output using repeatable validation; I will move forward only after this clears.',
    'I am validating the latest output using repeatable validation; I will share a clear pass/fail summary next.',
    'I am validating the latest output using repeatable validation; I will call out any issue before continuing.',
    'I am validating the latest output using repeatable validation; I will keep this verification concise and transparent.',
    'I am validating the latest output using repeatable validation; I will report what changed and why it is safe.',
    'I am validating the latest output using repeatable validation; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output to ensure stable progression; I will move forward only after this clears.',
    'I am validating the latest output to ensure stable progression; I will share a clear pass/fail summary next.',
    'I am validating the latest output to ensure stable progression; I will call out any issue before continuing.',
    'I am validating the latest output to ensure stable progression; I will keep this verification concise and transparent.',
    'I am validating the latest output to ensure stable progression; I will report what changed and why it is safe.',
    'I am validating the latest output to ensure stable progression; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output with reproducibility in mind; I will move forward only after this clears.',
    'I am validating the latest output with reproducibility in mind; I will share a clear pass/fail summary next.',
    'I am validating the latest output with reproducibility in mind; I will call out any issue before continuing.',
    'I am validating the latest output with reproducibility in mind; I will keep this verification concise and transparent.',
    'I am validating the latest output with reproducibility in mind; I will report what changed and why it is safe.',
    'I am validating the latest output with reproducibility in mind; I will proceed once this checkpoint is confirmed.',
    'I am validating the latest output so we only advance on success; I will move forward only after this clears.',
    'I am validating the latest output so we only advance on success; I will share a clear pass/fail summary next.',
    'I am validating the latest output so we only advance on success; I will call out any issue before continuing.',
    'I am validating the latest output so we only advance on success; I will keep this verification concise and transparent.',
    'I am validating the latest output so we only advance on success; I will report what changed and why it is safe.',
    'I am validating the latest output so we only advance on success; I will proceed once this checkpoint is confirmed.',
  ],
  'next-step': [
    'I am preparing the next visible step from the current results; I will start it immediately after this update.',
    'I am preparing the next visible step from the current results; I will confirm when the next step begins.',
    'I am preparing the next visible step from the current results; I will keep the transition explicit and clear.',
    'I am preparing the next visible step from the current results; I will post the next status as soon as it starts.',
    'I am preparing the next visible step from the current results; I will continue with the safest available move.',
    'I am preparing the next visible step from the current results; I will maintain continuity and report progress.',
    'I am preparing the next visible step based on the latest verification; I will start it immediately after this update.',
    'I am preparing the next visible step based on the latest verification; I will confirm when the next step begins.',
    'I am preparing the next visible step based on the latest verification; I will keep the transition explicit and clear.',
    'I am preparing the next visible step based on the latest verification; I will post the next status as soon as it starts.',
    'I am preparing the next visible step based on the latest verification; I will continue with the safest available move.',
    'I am preparing the next visible step based on the latest verification; I will maintain continuity and report progress.',
    'I am preparing the next visible step with clear success criteria; I will start it immediately after this update.',
    'I am preparing the next visible step with clear success criteria; I will confirm when the next step begins.',
    'I am preparing the next visible step with clear success criteria; I will keep the transition explicit and clear.',
    'I am preparing the next visible step with clear success criteria; I will post the next status as soon as it starts.',
    'I am preparing the next visible step with clear success criteria; I will continue with the safest available move.',
    'I am preparing the next visible step with clear success criteria; I will maintain continuity and report progress.',
    'I am preparing the next visible step while keeping the timeline readable; I will start it immediately after this update.',
    'I am preparing the next visible step while keeping the timeline readable; I will confirm when the next step begins.',
    'I am preparing the next visible step while keeping the timeline readable; I will keep the transition explicit and clear.',
    'I am preparing the next visible step while keeping the timeline readable; I will post the next status as soon as it starts.',
    'I am preparing the next visible step while keeping the timeline readable; I will continue with the safest available move.',
    'I am preparing the next visible step while keeping the timeline readable; I will maintain continuity and report progress.',
    'I am preparing the next visible step without losing execution context; I will start it immediately after this update.',
    'I am preparing the next visible step without losing execution context; I will confirm when the next step begins.',
    'I am preparing the next visible step without losing execution context; I will keep the transition explicit and clear.',
    'I am preparing the next visible step without losing execution context; I will post the next status as soon as it starts.',
    'I am preparing the next visible step without losing execution context; I will continue with the safest available move.',
    'I am preparing the next visible step without losing execution context; I will maintain continuity and report progress.',
    'I am preparing the next visible step with dependencies already accounted for; I will start it immediately after this update.',
    'I am preparing the next visible step with dependencies already accounted for; I will confirm when the next step begins.',
    'I am preparing the next visible step with dependencies already accounted for; I will keep the transition explicit and clear.',
    'I am preparing the next visible step with dependencies already accounted for; I will post the next status as soon as it starts.',
    'I am preparing the next visible step with dependencies already accounted for; I will continue with the safest available move.',
    'I am preparing the next visible step with dependencies already accounted for; I will maintain continuity and report progress.',
    'I am preparing the next visible step with rollback awareness; I will start it immediately after this update.',
    'I am preparing the next visible step with rollback awareness; I will confirm when the next step begins.',
    'I am preparing the next visible step with rollback awareness; I will keep the transition explicit and clear.',
    'I am preparing the next visible step with rollback awareness; I will post the next status as soon as it starts.',
    'I am preparing the next visible step with rollback awareness; I will continue with the safest available move.',
    'I am preparing the next visible step with rollback awareness; I will maintain continuity and report progress.',
    'I am preparing the next visible step with priority on user impact; I will start it immediately after this update.',
    'I am preparing the next visible step with priority on user impact; I will confirm when the next step begins.',
    'I am preparing the next visible step with priority on user impact; I will keep the transition explicit and clear.',
    'I am preparing the next visible step with priority on user impact; I will post the next status as soon as it starts.',
    'I am preparing the next visible step with priority on user impact; I will continue with the safest available move.',
    'I am preparing the next visible step with priority on user impact; I will maintain continuity and report progress.',
    'I am preparing the next visible step using the current state as baseline; I will start it immediately after this update.',
    'I am preparing the next visible step using the current state as baseline; I will confirm when the next step begins.',
    'I am preparing the next visible step using the current state as baseline; I will keep the transition explicit and clear.',
    'I am preparing the next visible step using the current state as baseline; I will post the next status as soon as it starts.',
    'I am preparing the next visible step using the current state as baseline; I will continue with the safest available move.',
    'I am preparing the next visible step using the current state as baseline; I will maintain continuity and report progress.',
    'I am preparing the next visible step with minimal disruption; I will start it immediately after this update.',
    'I am preparing the next visible step with minimal disruption; I will confirm when the next step begins.',
    'I am preparing the next visible step with minimal disruption; I will keep the transition explicit and clear.',
    'I am preparing the next visible step with minimal disruption; I will post the next status as soon as it starts.',
    'I am preparing the next visible step with minimal disruption; I will continue with the safest available move.',
    'I am preparing the next visible step with minimal disruption; I will maintain continuity and report progress.',
  ],
  recovery: [
    'I am recovering from an interruption without dropping your context; I will continue once stability is restored.',
    'I am recovering from an interruption without dropping your context; I will report the recovery outcome next.',
    'I am recovering from an interruption without dropping your context; I will stop and surface details if this repeats.',
    'I am recovering from an interruption without dropping your context; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption without dropping your context; I will confirm when normal execution resumes.',
    'I am recovering from an interruption without dropping your context; I will proceed with the safest validated option.',
    'I am recovering from an interruption with explicit retry controls; I will continue once stability is restored.',
    'I am recovering from an interruption with explicit retry controls; I will report the recovery outcome next.',
    'I am recovering from an interruption with explicit retry controls; I will stop and surface details if this repeats.',
    'I am recovering from an interruption with explicit retry controls; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption with explicit retry controls; I will confirm when normal execution resumes.',
    'I am recovering from an interruption with explicit retry controls; I will proceed with the safest validated option.',
    'I am recovering from an interruption while preserving completed work; I will continue once stability is restored.',
    'I am recovering from an interruption while preserving completed work; I will report the recovery outcome next.',
    'I am recovering from an interruption while preserving completed work; I will stop and surface details if this repeats.',
    'I am recovering from an interruption while preserving completed work; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption while preserving completed work; I will confirm when normal execution resumes.',
    'I am recovering from an interruption while preserving completed work; I will proceed with the safest validated option.',
    'I am recovering from an interruption with diagnostics captured; I will continue once stability is restored.',
    'I am recovering from an interruption with diagnostics captured; I will report the recovery outcome next.',
    'I am recovering from an interruption with diagnostics captured; I will stop and surface details if this repeats.',
    'I am recovering from an interruption with diagnostics captured; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption with diagnostics captured; I will confirm when normal execution resumes.',
    'I am recovering from an interruption with diagnostics captured; I will proceed with the safest validated option.',
    'I am recovering from an interruption and protective backoff enabled; I will continue once stability is restored.',
    'I am recovering from an interruption and protective backoff enabled; I will report the recovery outcome next.',
    'I am recovering from an interruption and protective backoff enabled; I will stop and surface details if this repeats.',
    'I am recovering from an interruption and protective backoff enabled; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption and protective backoff enabled; I will confirm when normal execution resumes.',
    'I am recovering from an interruption and protective backoff enabled; I will proceed with the safest validated option.',
    'I am recovering from an interruption with clear guardrails applied; I will continue once stability is restored.',
    'I am recovering from an interruption with clear guardrails applied; I will report the recovery outcome next.',
    'I am recovering from an interruption with clear guardrails applied; I will stop and surface details if this repeats.',
    'I am recovering from an interruption with clear guardrails applied; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption with clear guardrails applied; I will confirm when normal execution resumes.',
    'I am recovering from an interruption with clear guardrails applied; I will proceed with the safest validated option.',
    'I am recovering from an interruption while avoiding repeat failures; I will continue once stability is restored.',
    'I am recovering from an interruption while avoiding repeat failures; I will report the recovery outcome next.',
    'I am recovering from an interruption while avoiding repeat failures; I will stop and surface details if this repeats.',
    'I am recovering from an interruption while avoiding repeat failures; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption while avoiding repeat failures; I will confirm when normal execution resumes.',
    'I am recovering from an interruption while avoiding repeat failures; I will proceed with the safest validated option.',
    'I am recovering from an interruption and preparing a stable continuation; I will continue once stability is restored.',
    'I am recovering from an interruption and preparing a stable continuation; I will report the recovery outcome next.',
    'I am recovering from an interruption and preparing a stable continuation; I will stop and surface details if this repeats.',
    'I am recovering from an interruption and preparing a stable continuation; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption and preparing a stable continuation; I will confirm when normal execution resumes.',
    'I am recovering from an interruption and preparing a stable continuation; I will proceed with the safest validated option.',
    'I am recovering from an interruption with safety-first decision rules; I will continue once stability is restored.',
    'I am recovering from an interruption with safety-first decision rules; I will report the recovery outcome next.',
    'I am recovering from an interruption with safety-first decision rules; I will stop and surface details if this repeats.',
    'I am recovering from an interruption with safety-first decision rules; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption with safety-first decision rules; I will confirm when normal execution resumes.',
    'I am recovering from an interruption with safety-first decision rules; I will proceed with the safest validated option.',
    'I am recovering from an interruption and full visibility in the timeline; I will continue once stability is restored.',
    'I am recovering from an interruption and full visibility in the timeline; I will report the recovery outcome next.',
    'I am recovering from an interruption and full visibility in the timeline; I will stop and surface details if this repeats.',
    'I am recovering from an interruption and full visibility in the timeline; I will keep recovery transparent and controlled.',
    'I am recovering from an interruption and full visibility in the timeline; I will confirm when normal execution resumes.',
    'I am recovering from an interruption and full visibility in the timeline; I will proceed with the safest validated option.',
  ],
} as const;

export const COMMENTARY_POOL_SIZE = 300;

export function getCommentaryPoolMessage(phase: AgentCommentaryPhase, seed: number, fallback: string): string {
  const pool = COMMENTARY_POOL_BY_PHASE[phase];

  if (!pool || pool.length === 0) {
    return fallback;
  }

  if (!Number.isFinite(seed)) {
    return pool[0] || fallback;
  }

  const normalizedSeed = Math.abs(Math.trunc(seed));
  const index = normalizedSeed % pool.length;

  return pool[index] || fallback;
}
